"""
bot/tickers.py
--------------
Nifty 500 universe. No imports — safe to use anywhere.
Update annually as index constituents change.
"""

import pandas as pd

# _RAW = [
#     '360ONE', '3MINDIA', 'AARTIDRUGS', 'AARTIIND', 'AAVAS',
#     'ABB', 'ABBOTINDIA', 'ABCAPITAL', 'ABFRL', 'ACC',
#     'ACE', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER',
#     'AEGISCHEM', 'AFFLE', 'AIAENG', 'AJANTPHARM', 'APLAPOLLO',
#     'APOLLOHOSP', 'APOLLOTYRE', 'APTUS', 'ASAHIINDIA', 'ASHOKLEY',
#     'ASIANPAINT', 'ASTERDM', 'ASTRAL', 'ATUL', 'AUBANK',
#     'AUROPHARMA', 'AVANTIFEED', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJCON',
#     'BAJAJELEC', 'BAJFINANCE', 'BAJAJFINSV', 'BAJAJHLDNG', 'BALAMINES',
#     'BALKRISIND', 'BALRAMCHIN', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA',
#     'MAHABANK', 'BATAINDIA', 'BAYERCROP', 'BDL', 'BEL',
#     'BEML', 'BERGEPAINT', 'BHARATFORG', 'BHEL', 'BPCL',
#     'BHARTIARTL', 'BIKAJI', 'BIOCON', 'BIRLACORPN', 'BSOFT',
#     'BLUEDART', 'BLUESTARCO', 'BOSCHLTD', 'BRIGADE', 'BRITANNIA',
#     'CANFINHOME', 'CANBK', 'CAPLIPOINT', 'CARBORUNIV', 'CASTROLIND',
#     'CEATLTD', 'CENTRALBK', 'CDSL', 'CENTURYPLY', 'CENTURYTEX',
#     'CERA', 'CESC', 'CGPOWER', 'CHALET', 'CHAMBLFERT',
#     'CHOLAFIN', 'CIPLA', 'CUB', 'COALINDIA', 'COCHINSHIP',
#     'COFORGE', 'COLPAL', 'CONCOR', 'COROMANDEL', 'CREDITACC',
#     'CRISIL', 'CROMPTON', 'CSBBANK', 'CUMMINSIND', 'CYIENT',
#     'DABUR', 'DALBHARAT', 'DATAPATTNS', 'DCMSHRIRAM', 'DEEPAKNTR',
#     'DELHIVERY', 'DEVYANI', 'DIVISLAB', 'DIXON', 'DLF',
#     'DRREDDY', 'ECLERX', 'EDELWEISS', 'EICHERMOT', 'EIDPARRY',
#     'EIHOTEL', 'ELGIEQUIP', 'EMAMILTD', 'ENDURANCE', 'ENGINERSIN',
#     'EQUITASBNK', 'ERIS', 'ESCORTS', 'EXIDEIND', 'FDC',
#     'FEDERALBNK', 'FINEORG', 'FINCABLES', 'FIVESTAR', 'FORTIS',
#     'GAIL', 'GMRINFRA', 'GLAND', 'GLAXO', 'GLENMARK',
#     'GNFC', 'GODFRYPHLP', 'GODREJAGRO', 'GODREJCP', 'GODREJIND',
#     'GODREJPROP', 'GRANULES', 'GRAPHITE', 'GRASIM', 'GRINDWELL',
#     'GUJALKALI', 'GUJGASLTD', 'GSFC', 'GSPL', 'HAL',
#     'HAVELLS', 'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE',
#     'HEG', 'HEROMOTOCO', 'HFCL', 'HIKAL', 'HINDALCO',
#     'HINDCOPPER', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HOMEFIRST',
#     'HUDCO', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'ISEC',
#     'IDBI', 'IDFCFIRSTB', 'NAUKRI', 'INFY', 'INTELLECT',
#     'IPCALAB', 'IRB', 'IRCTC', 'IRFC', 'ITC',
#     'JBCHEPHARM', 'JSL', 'JSWENERGY', 'JSWSTEEL', 'JUBLFOOD',
#     'JUSTDIAL', 'JYOTHYLAB', 'KPRMILL', 'KAJARIACER', 'KALPATPOWR',
#     'KALYANKJIL', 'KANSAINER', 'KARURVYSYA', 'KAYNES', 'KEC',
#     'KEI', 'KIMS', 'KNRCON', 'KOTAKBANK', 'KRBL',
#     'KSB', 'KFINTECH', 'LTTS', 'LAXMIMACH', 'LICI',
#     'LT', 'LTIM', 'LAURUSLABS', 'LEMONTREE', 'LINDEINDIA',
#     'LUPIN', 'LUXIND', 'M&M', 'M&MFIN', 'MAHINDCIE',
#     'MGL', 'MANAPPURAM', 'MARICO', 'MARUTI', 'MASTEK',
#     'MAXHEALTH', 'METROPOLIS', 'MFSL', 'MOTILALOFS', 'MPHASIS',
#     'MCX', 'MRF', 'MUTHOOTFIN', 'NATCOPHARM', 'NATIONALUM',
#     'NAVINFLUOR', 'NBCC', 'NCC', 'NESTLEIND', 'NHPC',
#     'NLCINDIA', 'NMDC', 'NTPC', 'OBEROIRLTY', 'ONGC',
#     'OFSS', 'PCBL', 'PIIND', 'PNB', 'PNCINFRA',
#     'PVRINOX', 'PAGEIND', 'PERSISTENT', 'PETRONET', 'PFIZER',
#     'PHOENIXLTD', 'PIDILITIND', 'PEL', 'POLYMED', 'POLYCAB',
#     'POONAWALLA', 'PFC', 'POWERGRID', 'PRESTIGE', 'PRINCEPIPE',
#     'PTC', 'RBLBANK', 'RECLTD', 'RITES', 'RADICO',
#     'RVNL', 'RAILTEL', 'RAIN', 'RAJESHEXPO', 'RALLIS',
#     'RATNAMANI', 'RAYMOND', 'REDINGTON', 'RELAXO', 'RELIANCE',
#     'RHIM', 'ROUTE', 'SBICARD', 'SBILIFE', 'SAIL',
#     'SANOFI', 'SAPPHIRE', 'SAREGAMA', 'SCHAEFFLER', 'SHRIRAMFIN',
#     'SIEMENS', 'SJVN', 'SKFINDIA', 'SOBHA', 'SOLARINDS',
#     'SONACOMS', 'SONATSOFTW', 'SRF', 'STARHEALTH', 'SBIN',
#     'STLTECH', 'SUMICHEM', 'SUNDARMFIN', 'SUNDRMFAST', 'SUNPHARMA',
#     'SUNTV', 'SUPRAJIT', 'SUPREMEIND', 'SUZLON', 'SYMPHONY',
#     'SYNGENE', 'TANLA', 'TATACHEM', 'TATACOMM', 'TCS',
#     'TATACONSUM', 'TATAELXSI', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL',
#     'TEAMLEASE', 'TECHM', 'RAMCOCEM', 'THERMAX', 'TIMKEN',
#     'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TRENT', 'TRIDENT',
#     'TRITURBINE', 'TVSMOTOR', 'ULTRACEMCO', 'UNIONBANK', 'UBL',
#     'UPL', 'UTIAMC', 'VGUARD', 'VTL', 'VEDL',
#     'VOLTAS', 'WELCORP', 'WELSPUNLIV', 'WESTLIFE', 'WIPRO',
#     'WONDERLA', 'YESBANK', 'ZEEL', 'ZENSARTECH', 'ZYDUSLIFE',
#     'ZYDUSWELL', 'ZOMATO', 'DMART', 'INDIGO',
# ]

_RAW = pd.read_csv("ind_nifty500list.csv")["Symbol"].dropna().str.strip().tolist()

# Deduplicate while preserving order
_seen = set()
NIFTY500 = [t for t in _RAW if t not in _seen and not _seen.add(t)]

NIFTY50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",
    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",
    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "TITAN",
    "SUNPHARMA", "ULTRACEMCO", "WIPRO", "NESTLEIND", "POWERGRID",
    "NTPC", "TECHM", "HCLTECH", "BAJFINANCE", "BAJAJFINSV",
    "ONGC", "COALINDIA", "TATAMOTORS", "TATASTEEL", "JSWSTEEL",
    "ADANIENT", "ADANIPORTS", "GRASIM", "DIVISLAB", "DRREDDY",
    "CIPLA", "EICHERMOT", "HEROMOTOCO", "BPCL", "INDUSINDBK",
    "M&M", "BRITANNIA", "APOLLOHOSP", "TATACONSUM", "HINDALCO",
    "VEDL", "UPL", "SBILIFE", "HDFCLIFE", "BAJAJ-AUTO",
]